using OpenCallMesh.Transport;
using OpenCallMesh.Domain;
using System.Net;
using System.Net.Sockets;
using System.Text;
using System.Threading;
var port=19000+Random.Shared.Next(500);
using var cts=new CancellationTokenSource(TimeSpan.FromSeconds(5));
var received=new TaskCompletionSource<string>();
var server=new LineTransport();
var run=server.RunServerAsync(new IPEndPoint(IPAddress.Loopback,port),s=>{received.TrySetResult(s);return Task.CompletedTask;},cts.Token);
await Task.Delay(50,cts.Token); await LineTransport.SendAsync("127.0.0.1",port,"synthetic",cts.Token);
if(await received.Task != "synthetic") throw new Exception("Transport failed");
cts.Cancel();
var mediaPort = 19171;
var mediaReceived = new TaskCompletionSource<AudioFrame>(TaskCreationOptions.RunContinuationsAsynchronously);
using var mediaCts = new CancellationTokenSource(TimeSpan.FromSeconds(5));
var mediaServer = new MediaFrameTransport().RunServerAsync(new IPEndPoint(IPAddress.Loopback, mediaPort), frame => { mediaReceived.TrySetResult(frame); return Task.CompletedTask; }, mediaCts.Token);
await Task.Delay(50, mediaCts.Token);
var expectedFrame = new AudioFrame("stream", "agent-a", "telegram", 7, 123, [1, 2, 3]);
await MediaFrameTransport.SendAsync("127.0.0.1", mediaPort, expectedFrame, mediaCts.Token);
var actualFrame = await mediaReceived.Task.WaitAsync(mediaCts.Token);
if (actualFrame with { Payload = [] } != expectedFrame with { Payload = [] } || !actualFrame.Payload.SequenceEqual(expectedFrame.Payload)) throw new Exception("Media frame transport failed");
mediaCts.Cancel();
Console.WriteLine("Transport tests passed");
